### ISSUE TITLE
feature: Allow people to define their own PGWEB_DATABASE_URL

### ISSUE THREAD

**Issue by violuke** [lrstanley/helm-charts#56]
### ✨ Describe the feature you'd like

`PGWEB_DATABASE_URL` is [hard-coded](https://github.com/lrstanley/helm-charts/blob/master/charts/pgweb/templates/deployment.yaml#L46), which makes using this chart a pain for me.

I'd like to be able to configure this env var like:
```yaml
pgweb:
  environment:
    - name: PGWEB_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: my-existing-secret
          key: my_key
  ingress:
    enabled: true
```

### 🌧 Is your feature request related to a problem?

Yes, the chart forces a configuration scheme which is unhelpful if people already have a secret with the required information available.,

### 🔎 Describe alternatives you've considered

-

### ⚠ If implemented, do you think this feature will be a breaking change to users?

No

### ⚙ Additional context

This should be able to be implemented without it being a breaking change.

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [ ] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.
